CREATE TABLE afl_mens_match (
    -- Match Information
    awayId                VARCHAR(50)   DEFAULT NULL,
    behinds               INT           DEFAULT NULL,
    blocks                INT           DEFAULT NULL,
    clangers              INT           DEFAULT NULL,
    clearances            INT           DEFAULT NULL,
    disposalEfficiency    INT           DEFAULT NULL,
    disposals             INT           DEFAULT NULL,
    displayName           VARCHAR(50)   DEFAULT NULL,
    fixtureId             VARCHAR(50)   NOT NULL,
    fixtureYear           VARCHAR(50)   NOT NULL,
    firstname             VARCHAR(50)   DEFAULT NULL,  -- Adjusted to match CSV
    freesAgainst          INT           DEFAULT NULL,
    freesFor              INT           DEFAULT NULL,
    goalAssists           INT           DEFAULT NULL,
    goals                 INT           DEFAULT NULL,
    handballs             INT           DEFAULT NULL,
    hitouts               INT           DEFAULT NULL,
    hitoutsToAdvantage    INT           DEFAULT NULL,
    homeId                VARCHAR(50)   NOT NULL,
    inside50s             INT           DEFAULT NULL,
    jumperNumber          INT           DEFAULT NULL,
    kicks                 INT           DEFAULT NULL,
    kicksEffective        INT           DEFAULT NULL,
    kicksIneffective      INT           DEFAULT NULL,
    kickEfficiency        INT           DEFAULT NULL,
    marks                 INT           DEFAULT NULL,
    marksContested        INT           DEFAULT NULL,
    marksInside50         INT           DEFAULT NULL,
    marksUncontested      INT           DEFAULT NULL,
    matchId               VARCHAR(50)   NOT NULL,
    opponent              VARCHAR(100)  DEFAULT NULL,
    penalty50sAgainst     INT           DEFAULT NULL,
    playerId              VARCHAR(50)   NOT NULL,
    positionCode          VARCHAR(50)   DEFAULT NULL,
    positionId            VARCHAR(50)   DEFAULT NULL,
    positionName          VARCHAR(50)   DEFAULT NULL,
    possessionsContested  INT           DEFAULT NULL,
    possessionsUncontested INT          DEFAULT NULL,
    round                 INT           DEFAULT NULL,
    shortDisplayName      VARCHAR(50)   DEFAULT NULL,
    sportId               VARCHAR(50)   NOT NULL,
    squadId               VARCHAR(50)   NOT NULL,
    squadName             VARCHAR(100)  DEFAULT NULL,
    surname               VARCHAR(50)   DEFAULT NULL,
    tackles               INT           DEFAULT NULL,

    -- Precomputed Columns
    uniqueFixtureId       VARCHAR(255)  NOT NULL,
    uniqueMatchId         VARCHAR(255)  NOT NULL,
    uniquePlayerId        VARCHAR(255)  NOT NULL,
    uniqueSquadId         VARCHAR(255)  NOT NULL,
    uniqueSportId         VARCHAR(255)  NOT NULL,

    -- Primary Key
    PRIMARY KEY (uniqueMatchId),

    -- Foreign Keys
    FOREIGN KEY (uniqueFixtureId) REFERENCES afl_mens_fixture(uniqueFixtureId),
    FOREIGN KEY (uniquePlayerId)  REFERENCES player_info(uniquePlayerId),
    FOREIGN KEY (uniqueSquadId)   REFERENCES squad_info(uniqueSquadId),
    FOREIGN KEY (uniqueSportId)   REFERENCES sport_info(uniqueSportId)
);
